export default function Index() {
    return (
        <div className="flex flex-col">
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
            <span>hi!</span>
        </div>
    )
}