name: Build & Push Docker Container

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV \ 
          
      - name: Login To Private Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: seebeckzachary/pomotask:latest, seebeckzachary/pomotask:${{ env.RELEASE_VERSION }}
          secrets: |
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "NODE_ENV=production"